min_version = "2026.8.3"

[settings]
locked = true

[tools]
go = "1.26.5"
"github:goreleaser/goreleaser" = "2.17.1"
"github:anchore/syft" = "1.51.0"
"npm:@fission-ai/openspec" = "1.8.0"
"github:lycheeverse/lychee" = "lychee-v0.24.2"
node = "26.7.0"
