#!/bin/sh
# Synchronize canonical GitLab main to the GitHub mirror without copying
# GitLab commit history or its author identity. The mirror gets a new
# GitHub-identity commit with exactly the canonical source tree.
set -eu

remote=${AIGW_GITHUB_MIRROR_REMOTE:-github-mirror}
branch=${AIGW_GITHUB_MIRROR_BRANCH:-main}
github_name=${AIGW_GITHUB_AUTHOR_NAME:-HengYang}
github_email=${AIGW_GITHUB_AUTHOR_EMAIL:-hengyang.2003@tsinghua.org.cn}

case "$github_email" in
  hengyang.2003@tsinghua.org.cn) ;;
  *) echo "GitHub mirror identity must be hengyang.2003@tsinghua.org.cn" >&2; exit 2 ;;
esac

git rev-parse --is-inside-work-tree >/dev/null
git diff --quiet && git diff --cached --quiet || {
  echo "refusing mirror sync with a dirty worktree" >&2
  exit 2
}
remote_url=$(git remote get-url "$remote")
case "$remote_url" in
  *github.com*) ;;
  *) echo "mirror remote $remote is not a GitHub remote" >&2; exit 2 ;;
esac

canonical=$(git rev-parse "$branch")
tree=$(git rev-parse "$canonical^{tree}")
git fetch --no-tags "$remote" "refs/heads/$branch:refs/remotes/$remote/$branch"
parent=$(git rev-parse "refs/remotes/$remote/$branch")
if [ "$(git rev-parse "$parent^{tree}")" = "$tree" ]; then
  printf 'GitHub mirror already matches canonical %s (%s)\n' "$branch" "$canonical"
  exit 0
fi

snapshot=$(printf '%s\n\n%s\n%s\n' \
  'mirror: synchronize GitHub source snapshot' \
  "Canonical GitLab source commit: $canonical" \
  'Generated by scripts/git-github-mirror-sync.sh; do not push canonical GitLab history to GitHub.' \
  | GIT_AUTHOR_NAME="$github_name" GIT_AUTHOR_EMAIL="$github_email" \
    GIT_COMMITTER_NAME="$github_name" GIT_COMMITTER_EMAIL="$github_email" \
    git commit-tree "$tree" -p "$parent")

# `--force-with-lease` makes concurrent GitHub mirror changes fail closed.
git push --force-with-lease="refs/heads/$branch:$parent" "$remote" "${snapshot}:refs/heads/$branch"
git update-ref "refs/remotes/$remote/$branch" "$snapshot" "$parent"
printf 'GitHub mirror synchronized: %s\n' "$snapshot"
